module.exports = [
  {
    'requirement':{
      'process':'B',
      'pageNumber':2,
      'mode':'read'
    },
    frames:[
      {
        'process':'B',
        'pageNumber':2,
        'referenced':false,
        'modified':false,
        'pageFault':true,
        'required':true,
        'finished':false,
        'reservedForPageBuffering':false
      }
    ],
    'potentialVictims':[
      {
        'process':'B',
        'pageNumber':2,
        'referenced':false,
        'modified':false
      }
    ],
    'pageFault':true,
    'victim':undefined
  },
  {
    'requirement':{
      'process':'B',
      'pageNumber':4,
      'mode':'read'
    },
    frames:[
      {
        'process':'B',
        'pageNumber':2,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'B',
        'pageNumber':4,
        'referenced':false,
        'modified':false,
        'pageFault':true,
        'required':true,
        'finished':false,
        'reservedForPageBuffering':false
      }
    ],
    'potentialVictims':[
      {
        'process':'B',
        'pageNumber':2,
        'referenced':false,
        'modified':false
      },
      {
        'process':'B',
        'pageNumber':4,
        'referenced':false,
        'modified':false
      }
    ],
    'pageFault':true,
    'victim':undefined
  },
  {
    'requirement':{
      'process':'A',
      'pageNumber':1,
      'mode':'read'
    },
    frames:[
      {
        'process':'B',
        'pageNumber':2,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'B',
        'pageNumber':4,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':false,
        'modified':false,
        'pageFault':true,
        'required':true,
        'finished':false,
        'reservedForPageBuffering':false
      }
    ],
    'potentialVictims':[
      {
        'process':'B',
        'pageNumber':2,
        'referenced':false,
        'modified':false
      },
      {
        'process':'B',
        'pageNumber':4,
        'referenced':false,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':false,
        'modified':false
      }
    ],
    'pageFault':true,
    'victim':undefined
  },
  {
    'requirement':{
      'process':'A',
      'pageNumber':3,
      'mode':'read'
    },
    frames:[
      {
        'process':'B',
        'pageNumber':2,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'B',
        'pageNumber':4,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':3,
        'referenced':false,
        'modified':false,
        'pageFault':true,
        'required':true,
        'finished':false,
        'reservedForPageBuffering':false
      }
    ],
    'potentialVictims':[
      {
        'process':'B',
        'pageNumber':2,
        'referenced':false,
        'modified':false
      },
      {
        'process':'B',
        'pageNumber':4,
        'referenced':false,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':false,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':3,
        'referenced':false,
        'modified':false
      }
    ],
    'pageFault':true,
    'victim':undefined
  },
  {
    'requirement':{
      'process':'A',
      'pageNumber':1,
      'mode':'read'
    },
    frames:[
      {
        'process':'B',
        'pageNumber':2,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'B',
        'pageNumber':4,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':true,
        'modified':false,
        'pageFault':false,
        'required':true,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':3,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      }
    ],
    'potentialVictims':[
      {
        'process':'B',
        'pageNumber':2,
        'referenced':false,
        'modified':false
      },
      {
        'process':'B',
        'pageNumber':4,
        'referenced':false,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':true,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':3,
        'referenced':false,
        'modified':false
      }
    ],
    'pageFault':false,
    'victim':undefined
  },
  {
    'requirement':{
      'process':'C',
      'pageNumber':1,
      'mode':'read'
    },
    frames:[
      {
        'process':'B',
        'pageNumber':2,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'B',
        'pageNumber':4,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':true,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':3,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'C',
        'pageNumber':1,
        'referenced':false,
        'modified':false,
        'pageFault':true,
        'required':true,
        'finished':false,
        'reservedForPageBuffering':false
      }
    ],
    'potentialVictims':[
      {
        'process':'B',
        'pageNumber':2,
        'referenced':false,
        'modified':false
      },
      {
        'process':'B',
        'pageNumber':4,
        'referenced':false,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':true,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':3,
        'referenced':false,
        'modified':false
      },
      {
        'process':'C',
        'pageNumber':1,
        'referenced':false,
        'modified':false
      }
    ],
    'pageFault':true,
    'victim':undefined
  },
  {
    'requirement':{
      'process':'C',
      'pageNumber':2,
      'mode':'read'
    },
    frames:[
      {
        'process':'B',
        'pageNumber':2,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'B',
        'pageNumber':4,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':true,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':3,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'C',
        'pageNumber':1,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'C',
        'pageNumber':2,
        'referenced':false,
        'modified':false,
        'pageFault':true,
        'required':true,
        'finished':false,
        'reservedForPageBuffering':false
      }
    ],
    'potentialVictims':[
      {
        'process':'B',
        'pageNumber':2,
        'referenced':false,
        'modified':false
      },
      {
        'process':'B',
        'pageNumber':4,
        'referenced':false,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':true,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':3,
        'referenced':false,
        'modified':false
      },
      {
        'process':'C',
        'pageNumber':1,
        'referenced':false,
        'modified':false
      },
      {
        'process':'C',
        'pageNumber':2,
        'referenced':false,
        'modified':false
      }
    ],
    'pageFault':true,
    'victim':undefined
  },
  {
    'requirement':{
      'process':'B',
      'pageNumber':6,
      'mode':'read'
    },
    frames:[
      {
        'process':'B',
        'pageNumber':2,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'B',
        'pageNumber':4,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':true,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':3,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'C',
        'pageNumber':1,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'C',
        'pageNumber':2,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'B',
        'pageNumber':6,
        'referenced':false,
        'modified':false,
        'pageFault':true,
        'required':true,
        'finished':false,
        'reservedForPageBuffering':false
      }
    ],
    'potentialVictims':[
      {
        'process':'B',
        'pageNumber':2,
        'referenced':false,
        'modified':false
      },
      {
        'process':'B',
        'pageNumber':4,
        'referenced':false,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':true,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':3,
        'referenced':false,
        'modified':false
      },
      {
        'process':'C',
        'pageNumber':1,
        'referenced':false,
        'modified':false
      },
      {
        'process':'C',
        'pageNumber':2,
        'referenced':false,
        'modified':false
      },
      {
        'process':'B',
        'pageNumber':6,
        'referenced':false,
        'modified':false
      }
    ],
    'pageFault':true,
    'victim':undefined
  },
  {
    'requirement':{
      'process':'B',
      'pageNumber':2,
      'mode':'read'
    },
    frames:[
      {
        'process':'B',
        'pageNumber':2,
        'referenced':true,
        'modified':false,
        'pageFault':false,
        'required':true,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'B',
        'pageNumber':4,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':true,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':3,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'C',
        'pageNumber':1,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'C',
        'pageNumber':2,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'B',
        'pageNumber':6,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      }
    ],
    'potentialVictims':[
      {
        'process':'B',
        'pageNumber':2,
        'referenced':true,
        'modified':false
      },
      {
        'process':'B',
        'pageNumber':4,
        'referenced':false,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':true,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':3,
        'referenced':false,
        'modified':false
      },
      {
        'process':'C',
        'pageNumber':1,
        'referenced':false,
        'modified':false
      },
      {
        'process':'C',
        'pageNumber':2,
        'referenced':false,
        'modified':false
      },
      {
        'process':'B',
        'pageNumber':6,
        'referenced':false,
        'modified':false
      }
    ],
    'pageFault':false,
    'victim':undefined
  },
  {
    'requirement':{
      'process':'B',
      'pageNumber':4,
      'mode':'read'
    },
    frames:[
      {
        'process':'B',
        'pageNumber':2,
        'referenced':true,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'B',
        'pageNumber':4,
        'referenced':true,
        'modified':false,
        'pageFault':false,
        'required':true,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':true,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':3,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'C',
        'pageNumber':1,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'C',
        'pageNumber':2,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'B',
        'pageNumber':6,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      }
    ],
    'potentialVictims':[
      {
        'process':'B',
        'pageNumber':2,
        'referenced':true,
        'modified':false
      },
      {
        'process':'B',
        'pageNumber':4,
        'referenced':true,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':true,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':3,
        'referenced':false,
        'modified':false
      },
      {
        'process':'C',
        'pageNumber':1,
        'referenced':false,
        'modified':false
      },
      {
        'process':'C',
        'pageNumber':2,
        'referenced':false,
        'modified':false
      },
      {
        'process':'B',
        'pageNumber':6,
        'referenced':false,
        'modified':false
      }
    ],
    'pageFault':false,
    'victim':undefined
  },
  {
    'requirement':{
      'process':'A',
      'pageNumber':2,
      'mode':'read'
    },
    frames:[
      {
        'process':'B',
        'pageNumber':2,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'B',
        'pageNumber':4,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':2,
        'referenced':false,
        'modified':false,
        'pageFault':true,
        'required':true,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'C',
        'pageNumber':1,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'C',
        'pageNumber':2,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'B',
        'pageNumber':6,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      }
    ],
    'potentialVictims':[
      {
        'process':'C',
        'pageNumber':1,
        'referenced':false,
        'modified':false
      },
      {
        'process':'C',
        'pageNumber':2,
        'referenced':false,
        'modified':false
      },
      {
        'process':'B',
        'pageNumber':6,
        'referenced':false,
        'modified':false
      },
      {
        'process':'B',
        'pageNumber':2,
        'referenced':false,
        'modified':false
      },
      {
        'process':'B',
        'pageNumber':4,
        'referenced':false,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':false,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':2,
        'referenced':false,
        'modified':false
      }
    ],
    'pageFault':true,
    'victim':{
      'process':'A',
      'pageNumber':3,
      'referenced':false,
      'modified':false
    }
  },
  {
    'requirement':{
      'process':'A',
      'pageNumber':4,
      'mode':'read'
    },
    frames:[
      {
        'process':'B',
        'pageNumber':2,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'B',
        'pageNumber':4,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':2,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':4,
        'referenced':false,
        'modified':false,
        'pageFault':true,
        'required':true,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'C',
        'pageNumber':2,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'B',
        'pageNumber':6,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      }
    ],
    'potentialVictims':[
      {
        'process':'C',
        'pageNumber':2,
        'referenced':false,
        'modified':false
      },
      {
        'process':'B',
        'pageNumber':6,
        'referenced':false,
        'modified':false
      },
      {
        'process':'B',
        'pageNumber':2,
        'referenced':false,
        'modified':false
      },
      {
        'process':'B',
        'pageNumber':4,
        'referenced':false,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':false,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':2,
        'referenced':false,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':4,
        'referenced':false,
        'modified':false
      }
    ],
    'pageFault':true,
    'victim':{
      'process':'C',
      'pageNumber':1,
      'referenced':false,
      'modified':false
    }
  },
  {
    'requirement':{
      'process':'A',
      'pageNumber':1,
      'mode':'read'
    },
    frames:[
      {
        'process':'B',
        'pageNumber':2,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'B',
        'pageNumber':4,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':true,
        'modified':false,
        'pageFault':false,
        'required':true,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':2,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':4,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'C',
        'pageNumber':2,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'B',
        'pageNumber':6,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      }
    ],
    'potentialVictims':[
      {
        'process':'C',
        'pageNumber':2,
        'referenced':false,
        'modified':false
      },
      {
        'process':'B',
        'pageNumber':6,
        'referenced':false,
        'modified':false
      },
      {
        'process':'B',
        'pageNumber':2,
        'referenced':false,
        'modified':false
      },
      {
        'process':'B',
        'pageNumber':4,
        'referenced':false,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':true,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':2,
        'referenced':false,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':4,
        'referenced':false,
        'modified':false
      }
    ],
    'pageFault':false,
    'victim':undefined
  },
  {
    'requirement':{
      'process':'C',
      'pageNumber':4,
      'mode':'read'
    },
    frames:[
      {
        'process':'B',
        'pageNumber':2,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'B',
        'pageNumber':4,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':true,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':2,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':4,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'C',
        'pageNumber':4,
        'referenced':false,
        'modified':false,
        'pageFault':true,
        'required':true,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'B',
        'pageNumber':6,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      }
    ],
    'potentialVictims':[
      {
        'process':'B',
        'pageNumber':6,
        'referenced':false,
        'modified':false
      },
      {
        'process':'B',
        'pageNumber':2,
        'referenced':false,
        'modified':false
      },
      {
        'process':'B',
        'pageNumber':4,
        'referenced':false,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':true,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':2,
        'referenced':false,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':4,
        'referenced':false,
        'modified':false
      },
      {
        'process':'C',
        'pageNumber':4,
        'referenced':false,
        'modified':false
      }
    ],
    'pageFault':true,
    'victim':{
      'process':'C',
      'pageNumber':2,
      'referenced':false,
      'modified':false
    }
  },
  {
    'requirement':{
      'process':'C',
      'pageNumber':8,
      'mode':'read'
    },
    frames:[
      {
        'process':'B',
        'pageNumber':2,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'B',
        'pageNumber':4,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':true,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':2,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':4,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'C',
        'pageNumber':4,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'C',
        'pageNumber':8,
        'referenced':false,
        'modified':false,
        'pageFault':true,
        'required':true,
        'finished':false,
        'reservedForPageBuffering':false
      }
    ],
    'potentialVictims':[
      {
        'process':'B',
        'pageNumber':2,
        'referenced':false,
        'modified':false
      },
      {
        'process':'B',
        'pageNumber':4,
        'referenced':false,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':true,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':2,
        'referenced':false,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':4,
        'referenced':false,
        'modified':false
      },
      {
        'process':'C',
        'pageNumber':4,
        'referenced':false,
        'modified':false
      },
      {
        'process':'C',
        'pageNumber':8,
        'referenced':false,
        'modified':false
      }
    ],
    'pageFault':true,
    'victim':{
      'process':'B',
      'pageNumber':6,
      'referenced':false,
      'modified':false
    }
  },
  {
    'requirement':{
      'process':'B',
      'pageNumber':1,
      'mode':'read'
    },
    frames:[
      {
        'process':'B',
        'pageNumber':1,
        'referenced':false,
        'modified':false,
        'pageFault':true,
        'required':true,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'B',
        'pageNumber':4,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':true,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':2,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':4,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'C',
        'pageNumber':4,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'C',
        'pageNumber':8,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      }
    ],
    'potentialVictims':[
      {
        'process':'B',
        'pageNumber':4,
        'referenced':false,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':true,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':2,
        'referenced':false,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':4,
        'referenced':false,
        'modified':false
      },
      {
        'process':'C',
        'pageNumber':4,
        'referenced':false,
        'modified':false
      },
      {
        'process':'C',
        'pageNumber':8,
        'referenced':false,
        'modified':false
      },
      {
        'process':'B',
        'pageNumber':1,
        'referenced':false,
        'modified':false
      }
    ],
    'pageFault':true,
    'victim':{
      'process':'B',
      'pageNumber':2,
      'referenced':false,
      'modified':false
    }
  },
  {
    'requirement':{
      'process':'B',
      'pageNumber':8,
      'mode':'read'
    },
    frames:[
      {
        'process':'B',
        'pageNumber':1,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'B',
        'pageNumber':8,
        'referenced':false,
        'modified':false,
        'pageFault':true,
        'required':true,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':true,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':2,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':4,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'C',
        'pageNumber':4,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'C',
        'pageNumber':8,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      }
    ],
    'potentialVictims':[
      {
        'process':'A',
        'pageNumber':1,
        'referenced':true,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':2,
        'referenced':false,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':4,
        'referenced':false,
        'modified':false
      },
      {
        'process':'C',
        'pageNumber':4,
        'referenced':false,
        'modified':false
      },
      {
        'process':'C',
        'pageNumber':8,
        'referenced':false,
        'modified':false
      },
      {
        'process':'B',
        'pageNumber':1,
        'referenced':false,
        'modified':false
      },
      {
        'process':'B',
        'pageNumber':8,
        'referenced':false,
        'modified':false
      }
    ],
    'pageFault':true,
    'victim':{
      'process':'B',
      'pageNumber':4,
      'referenced':false,
      'modified':false
    }
  },
  {
    'requirement':{
      'process':'C',
      'pageNumber':6,
      'mode':'read'
    },
    frames:[
      {
        'process':'B',
        'pageNumber':1,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'B',
        'pageNumber':8,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'C',
        'pageNumber':6,
        'referenced':false,
        'modified':false,
        'pageFault':true,
        'required':true,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':4,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'C',
        'pageNumber':4,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'C',
        'pageNumber':8,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      }
    ],
    'potentialVictims':[
      {
        'process':'A',
        'pageNumber':4,
        'referenced':false,
        'modified':false
      },
      {
        'process':'C',
        'pageNumber':4,
        'referenced':false,
        'modified':false
      },
      {
        'process':'C',
        'pageNumber':8,
        'referenced':false,
        'modified':false
      },
      {
        'process':'B',
        'pageNumber':1,
        'referenced':false,
        'modified':false
      },
      {
        'process':'B',
        'pageNumber':8,
        'referenced':false,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':false,
        'modified':false
      },
      {
        'process':'C',
        'pageNumber':6,
        'referenced':false,
        'modified':false
      }
    ],
    'pageFault':true,
    'victim':{
      'process':'A',
      'pageNumber':2,
      'referenced':false,
      'modified':false
    }
  },
  {
    'requirement':{
      'process':'C',
      'pageNumber':1,
      'mode':'read'
    },
    frames:[
      {
        'process':'B',
        'pageNumber':1,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'B',
        'pageNumber':8,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'C',
        'pageNumber':6,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'C',
        'pageNumber':1,
        'referenced':false,
        'modified':false,
        'pageFault':true,
        'required':true,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'C',
        'pageNumber':4,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'C',
        'pageNumber':8,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      }
    ],
    'potentialVictims':[
      {
        'process':'C',
        'pageNumber':4,
        'referenced':false,
        'modified':false
      },
      {
        'process':'C',
        'pageNumber':8,
        'referenced':false,
        'modified':false
      },
      {
        'process':'B',
        'pageNumber':1,
        'referenced':false,
        'modified':false
      },
      {
        'process':'B',
        'pageNumber':8,
        'referenced':false,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':false,
        'modified':false
      },
      {
        'process':'C',
        'pageNumber':6,
        'referenced':false,
        'modified':false
      },
      {
        'process':'C',
        'pageNumber':1,
        'referenced':false,
        'modified':false
      }
    ],
    'pageFault':true,
    'victim':{
      'process':'A',
      'pageNumber':4,
      'referenced':false,
      'modified':false
    }
  },
  {
    'requirement':{
      'process':'C',
      'pageNumber':4,
      'mode':'read'
    },
    frames:[
      {
        'process':'B',
        'pageNumber':1,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'B',
        'pageNumber':8,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'C',
        'pageNumber':6,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'C',
        'pageNumber':1,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'C',
        'pageNumber':4,
        'referenced':true,
        'modified':false,
        'pageFault':false,
        'required':true,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'C',
        'pageNumber':8,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      }
    ],
    'potentialVictims':[
      {
        'process':'C',
        'pageNumber':4,
        'referenced':true,
        'modified':false
      },
      {
        'process':'C',
        'pageNumber':8,
        'referenced':false,
        'modified':false
      },
      {
        'process':'B',
        'pageNumber':1,
        'referenced':false,
        'modified':false
      },
      {
        'process':'B',
        'pageNumber':8,
        'referenced':false,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':false,
        'modified':false
      },
      {
        'process':'C',
        'pageNumber':6,
        'referenced':false,
        'modified':false
      },
      {
        'process':'C',
        'pageNumber':1,
        'referenced':false,
        'modified':false
      }
    ],
    'pageFault':false,
    'victim':undefined
  },
  {
    'requirement':{
      'process':'C',
      'pageNumber':1,
      'mode':'read'
    },
    frames:[
      {
        'process':'B',
        'pageNumber':1,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'B',
        'pageNumber':8,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'C',
        'pageNumber':6,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'C',
        'pageNumber':1,
        'referenced':true,
        'modified':false,
        'pageFault':false,
        'required':true,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'C',
        'pageNumber':4,
        'referenced':true,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'C',
        'pageNumber':8,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      }
    ],
    'potentialVictims':[
      {
        'process':'C',
        'pageNumber':4,
        'referenced':true,
        'modified':false
      },
      {
        'process':'C',
        'pageNumber':8,
        'referenced':false,
        'modified':false
      },
      {
        'process':'B',
        'pageNumber':1,
        'referenced':false,
        'modified':false
      },
      {
        'process':'B',
        'pageNumber':8,
        'referenced':false,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':false,
        'modified':false
      },
      {
        'process':'C',
        'pageNumber':6,
        'referenced':false,
        'modified':false
      },
      {
        'process':'C',
        'pageNumber':1,
        'referenced':true,
        'modified':false
      }
    ],
    'pageFault':false,
    'victim':undefined
  },
  {
    'requirement':{
      'process':'A',
      'pageNumber':5,
      'mode':'read'
    },
    frames:[
      {
        'process':'B',
        'pageNumber':1,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'B',
        'pageNumber':8,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'C',
        'pageNumber':6,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'C',
        'pageNumber':1,
        'referenced':true,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'C',
        'pageNumber':4,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':5,
        'referenced':false,
        'modified':false,
        'pageFault':true,
        'required':true,
        'finished':false,
        'reservedForPageBuffering':false
      }
    ],
    'potentialVictims':[
      {
        'process':'B',
        'pageNumber':1,
        'referenced':false,
        'modified':false
      },
      {
        'process':'B',
        'pageNumber':8,
        'referenced':false,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':false,
        'modified':false
      },
      {
        'process':'C',
        'pageNumber':6,
        'referenced':false,
        'modified':false
      },
      {
        'process':'C',
        'pageNumber':1,
        'referenced':true,
        'modified':false
      },
      {
        'process':'C',
        'pageNumber':4,
        'referenced':false,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':5,
        'referenced':false,
        'modified':false
      }
    ],
    'pageFault':true,
    'victim':{
      'process':'C',
      'pageNumber':8,
      'referenced':false,
      'modified':false
    }
  },
  {
    'requirement':{
      'process':'A',
      'pageNumber':1,
      'mode':'read'
    },
    frames:[
      {
        'process':'B',
        'pageNumber':1,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'B',
        'pageNumber':8,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':true,
        'modified':false,
        'pageFault':false,
        'required':true,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'C',
        'pageNumber':6,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'C',
        'pageNumber':1,
        'referenced':true,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'C',
        'pageNumber':4,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':5,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      }
    ],
    'potentialVictims':[
      {
        'process':'B',
        'pageNumber':1,
        'referenced':false,
        'modified':false
      },
      {
        'process':'B',
        'pageNumber':8,
        'referenced':false,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':true,
        'modified':false
      },
      {
        'process':'C',
        'pageNumber':6,
        'referenced':false,
        'modified':false
      },
      {
        'process':'C',
        'pageNumber':1,
        'referenced':true,
        'modified':false
      },
      {
        'process':'C',
        'pageNumber':4,
        'referenced':false,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':5,
        'referenced':false,
        'modified':false
      }
    ],
    'pageFault':false,
    'victim':undefined
  },
  {
    'requirement':{
      'process':'A',
      'pageNumber':4,
      'mode':'read'
    },
    frames:[
      {
        'process':'A',
        'pageNumber':4,
        'referenced':false,
        'modified':false,
        'pageFault':true,
        'required':true,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'B',
        'pageNumber':8,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':true,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'C',
        'pageNumber':6,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'C',
        'pageNumber':1,
        'referenced':true,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'C',
        'pageNumber':4,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':5,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      }
    ],
    'potentialVictims':[
      {
        'process':'B',
        'pageNumber':8,
        'referenced':false,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':true,
        'modified':false
      },
      {
        'process':'C',
        'pageNumber':6,
        'referenced':false,
        'modified':false
      },
      {
        'process':'C',
        'pageNumber':1,
        'referenced':true,
        'modified':false
      },
      {
        'process':'C',
        'pageNumber':4,
        'referenced':false,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':5,
        'referenced':false,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':4,
        'referenced':false,
        'modified':false
      }
    ],
    'pageFault':true,
    'victim':{
      'process':'B',
      'pageNumber':1,
      'referenced':false,
      'modified':false
    }
  },
  {
    'requirement':{
      'process':'B',
      'pageNumber':3,
      'mode':'read'
    },
    frames:[
      {
        'process':'A',
        'pageNumber':4,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'B',
        'pageNumber':3,
        'referenced':false,
        'modified':false,
        'pageFault':true,
        'required':true,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':true,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'C',
        'pageNumber':6,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'C',
        'pageNumber':1,
        'referenced':true,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'C',
        'pageNumber':4,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':5,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      }
    ],
    'potentialVictims':[
      {
        'process':'A',
        'pageNumber':1,
        'referenced':true,
        'modified':false
      },
      {
        'process':'C',
        'pageNumber':6,
        'referenced':false,
        'modified':false
      },
      {
        'process':'C',
        'pageNumber':1,
        'referenced':true,
        'modified':false
      },
      {
        'process':'C',
        'pageNumber':4,
        'referenced':false,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':5,
        'referenced':false,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':4,
        'referenced':false,
        'modified':false
      },
      {
        'process':'B',
        'pageNumber':3,
        'referenced':false,
        'modified':false
      }
    ],
    'pageFault':true,
    'victim':{
      'process':'B',
      'pageNumber':8,
      'referenced':false,
      'modified':false
    }
  },
  {
    'requirement':{
      'process':'B',
      'pageNumber':1,
      'mode':'read'
    },
    frames:[
      {
        'process':'A',
        'pageNumber':4,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'B',
        'pageNumber':3,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'B',
        'pageNumber':1,
        'referenced':false,
        'modified':false,
        'pageFault':true,
        'required':true,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'C',
        'pageNumber':1,
        'referenced':true,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'C',
        'pageNumber':4,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':5,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      }
    ],
    'potentialVictims':[
      {
        'process':'C',
        'pageNumber':1,
        'referenced':true,
        'modified':false
      },
      {
        'process':'C',
        'pageNumber':4,
        'referenced':false,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':5,
        'referenced':false,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':4,
        'referenced':false,
        'modified':false
      },
      {
        'process':'B',
        'pageNumber':3,
        'referenced':false,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':false,
        'modified':false
      },
      {
        'process':'B',
        'pageNumber':1,
        'referenced':false,
        'modified':false
      }
    ],
    'pageFault':true,
    'victim':{
      'process':'C',
      'pageNumber':6,
      'referenced':false,
      'modified':false
    }
  },
  {
    'requirement':{
      'process':'B',
      'pageNumber':8,
      'mode':'read'
    },
    frames:[
      {
        'process':'A',
        'pageNumber':4,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'B',
        'pageNumber':3,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'B',
        'pageNumber':1,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'C',
        'pageNumber':1,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'B',
        'pageNumber':8,
        'referenced':false,
        'modified':false,
        'pageFault':true,
        'required':true,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':5,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      }
    ],
    'potentialVictims':[
      {
        'process':'A',
        'pageNumber':5,
        'referenced':false,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':4,
        'referenced':false,
        'modified':false
      },
      {
        'process':'B',
        'pageNumber':3,
        'referenced':false,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':false,
        'modified':false
      },
      {
        'process':'B',
        'pageNumber':1,
        'referenced':false,
        'modified':false
      },
      {
        'process':'C',
        'pageNumber':1,
        'referenced':false,
        'modified':false
      },
      {
        'process':'B',
        'pageNumber':8,
        'referenced':false,
        'modified':false
      }
    ],
    'pageFault':true,
    'victim':{
      'process':'C',
      'pageNumber':4,
      'referenced':false,
      'modified':false
    }
  },
  {
    'requirement':{
      'process':'C',
      'pageNumber':0,
      'mode':'finish'
    },
    frames:[
      {
        'process':'A',
        'pageNumber':4,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'B',
        'pageNumber':3,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'B',
        'pageNumber':1,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'finished':true
      },
      {
        'process':'B',
        'pageNumber':8,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':5,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      }
    ],
    'potentialVictims':[
      {
        'process':'A',
        'pageNumber':5,
        'referenced':false,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':4,
        'referenced':false,
        'modified':false
      },
      {
        'process':'B',
        'pageNumber':3,
        'referenced':false,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':false,
        'modified':false
      },
      {
        'process':'B',
        'pageNumber':1,
        'referenced':false,
        'modified':false
      },
      {
        'process':'B',
        'pageNumber':8,
        'referenced':false,
        'modified':false
      }
    ],
    'pageFault':false,
    'victim':undefined
  },
  {
    'requirement':{
      'process':'A',
      'pageNumber':7,
      'mode':'read'
    },
    frames:[
      {
        'process':'A',
        'pageNumber':4,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'B',
        'pageNumber':3,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'B',
        'pageNumber':1,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':7,
        'referenced':false,
        'modified':false,
        'pageFault':true,
        'required':true,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'B',
        'pageNumber':8,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':5,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      }
    ],
    'potentialVictims':[
      {
        'process':'A',
        'pageNumber':5,
        'referenced':false,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':4,
        'referenced':false,
        'modified':false
      },
      {
        'process':'B',
        'pageNumber':3,
        'referenced':false,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':false,
        'modified':false
      },
      {
        'process':'B',
        'pageNumber':1,
        'referenced':false,
        'modified':false
      },
      {
        'process':'B',
        'pageNumber':8,
        'referenced':false,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':7,
        'referenced':false,
        'modified':false
      }
    ],
    'pageFault':true,
    'victim':undefined
  },
  {
    'requirement':{
      'process':'A',
      'pageNumber':9,
      'mode':'read'
    },
    frames:[
      {
        'process':'A',
        'pageNumber':4,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'B',
        'pageNumber':3,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'B',
        'pageNumber':1,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':7,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'B',
        'pageNumber':8,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':9,
        'referenced':false,
        'modified':false,
        'pageFault':true,
        'required':true,
        'finished':false,
        'reservedForPageBuffering':false
      }
    ],
    'potentialVictims':[
      {
        'process':'A',
        'pageNumber':4,
        'referenced':false,
        'modified':false
      },
      {
        'process':'B',
        'pageNumber':3,
        'referenced':false,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':false,
        'modified':false
      },
      {
        'process':'B',
        'pageNumber':1,
        'referenced':false,
        'modified':false
      },
      {
        'process':'B',
        'pageNumber':8,
        'referenced':false,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':7,
        'referenced':false,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':9,
        'referenced':false,
        'modified':false
      }
    ],
    'pageFault':true,
    'victim':{
      'process':'A',
      'pageNumber':5,
      'referenced':false,
      'modified':false
    }
  },
  {
    'requirement':{
      'process':'A',
      'pageNumber':4,
      'mode':'read'
    },
    frames:[
      {
        'process':'A',
        'pageNumber':4,
        'referenced':true,
        'modified':false,
        'pageFault':false,
        'required':true,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'B',
        'pageNumber':3,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'B',
        'pageNumber':1,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':7,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'B',
        'pageNumber':8,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'process':'A',
        'pageNumber':9,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      }
    ],
    'potentialVictims':[
      {
        'process':'A',
        'pageNumber':4,
        'referenced':true,
        'modified':false
      },
      {
        'process':'B',
        'pageNumber':3,
        'referenced':false,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':false,
        'modified':false
      },
      {
        'process':'B',
        'pageNumber':1,
        'referenced':false,
        'modified':false
      },
      {
        'process':'B',
        'pageNumber':8,
        'referenced':false,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':7,
        'referenced':false,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':9,
        'referenced':false,
        'modified':false
      }
    ],
    'pageFault':false,
    'victim':undefined
  },
  {
    'requirement':{
      'process':'B',
      'pageNumber':0,
      'mode':'finish'
    },
    frames:[
      {
        'process':'A',
        'pageNumber':4,
        'referenced':true,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'finished':true
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'finished':true
      },
      {
        'process':'A',
        'pageNumber':7,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      },
      {
        'finished':true
      },
      {
        'process':'A',
        'pageNumber':9,
        'referenced':false,
        'modified':false,
        'pageFault':false,
        'required':false,
        'finished':false,
        'reservedForPageBuffering':false
      }
    ],
    'potentialVictims':[
      {
        'process':'A',
        'pageNumber':4,
        'referenced':true,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':1,
        'referenced':false,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':7,
        'referenced':false,
        'modified':false
      },
      {
        'process':'A',
        'pageNumber':9,
        'referenced':false,
        'modified':false
      }
    ],
    'pageFault':false,
    'victim':undefined
  },
  {
    'requirement':{
      'process':'A',
      'pageNumber':0,
      'mode':'finish'
    },
    frames:[
      {
        'finished':true
      },
      {
        'finished':true
      },
      {
        'finished':true
      },
      {
        'finished':true
      },
      {
        'finished':true
      },
      {
        'finished':true
      },
      {
        'finished':true
      }
    ],
    'potentialVictims':[

    ],
    'pageFault':false,
    'victim':undefined
  }
];
